// Generated by `npm run cf:typegen`. Stub file kept in repo so the build
// works before wrangler types has been run locally; rerun cf:typegen after
// editing wrangler.jsonc to refresh the binding shape.
declare namespace Cloudflare {
  interface Env {
    ASSETS: Fetcher;
    IMAGES: ImagesBinding;
    DB: D1Database;
  }
}

interface ImagesBinding {
  input(body: ReadableStream | ArrayBuffer | Uint8Array | Blob): {
    transform(opts: { width?: number; height?: number }): {
      output(opts: { format: string; quality?: number }): Promise<{
        response(): Response;
      }>;
    };
  };
}

interface CloudflareEnv extends Cloudflare.Env {}
