name = "pages-cms"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
BASE_URL = "https://cms.leme.work"

[[d1_databases]]
binding = "DB"
database_name = "pages-cms"
database_id = "a7bcfcae-4822-418d-937f-e150b910621e"
